web:
  restart: always
  build: ./web
  ports:
    - "127.0.0.1:5000:8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app
    - /usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

#nginx:
#  restart: always
#  build: ./nginx/
#  ports:
#    - "8001:80"
#  volumes:
#    - /www/static
#  volumes_from:
#    - web
#  links:
#    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: always
  image: redis:latest
  volumes:
    - redisdata:/data

#cron:
#  restart: always
#  build: ./cron/
